### ISSUE TITLE
Warn in console about themeVariables

### ISSUE THREAD

**Issue by LemarinelNet** [PonchRobles/inertiajs-tables-laravel-query-builder#15]
<img width="1347" alt="image" src="https://github.com/PonchRobles/inertiajs-tables-laravel-query-builder/assets/10656218/123fc8ca-d265-4ecc-8ef8-6a9705c8fdf0">

It seems this is due to the `inject("themeVariables")` which is in the buttonWithDropdown component.

If themeVariable is not provided in createApp, the warnings pops in every page using the table.

**Comment by PonchRobles** [comment]
Provide "themeVariables" in your main app.js file.

https://github.com/PonchRobles/inertiajs-tables-laravel-query-builder?tab=readme-ov-file#customizations-available
