### ISSUE TITLE
Class "ProtoneMedia\LaravelQueryBuilderInertiaJs\Filters\Filter" not found

### ISSUE THREAD

**Issue by LemarinelNet** [PonchRobles/inertiajs-tables-laravel-query-builder#16]
When trying to add a selectFilter, I got the error `Class "ProtoneMedia\LaravelQueryBuilderInertiaJs\Filters\Filter" not found``

I've searched a bit in the code, it seems that PSR namespaces are not correctly set . This even leads to warnings on composer install : 

`Class ProtoneMedia\LaravelQueryBuilderInertiaJs\Filters\Filter located in ./vendor/ponchrobles/inertiajs-tables-laravel-query-builder/php/Filter.php does not comply with psr-4 autoloading standard. Skipping.`

I think you should : 
- refactor all code to remove ProtoneMedia a set your own name instead
- Move Filter file in Filters folder, since the namespace ends with \filters, or change the namespace !!

**Comment by PonchRobles** [comment]
I moved the filter file to the filters folder. #17 
At the moment I will not work on a refactor to the entire package.
